spring:
  application:
    name: PaymentService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?userSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '1234'
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update